name: Docker Image CI

on:
  push:
    tags:
      - "v*"
env:
  registry: ghcr.io
  image_name: ${{ github.repository }}

jobs:
  push_to_registry:
    name: Push image to Github Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Github Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Ubuntu version
        id: extract_metadata_ubuntu
        uses: docker/metadata-action@v4.1.0
        with:
          images: ${{ env.registry }}/${{ env.image_name }}

      - name: Extract metadata for Alpine version
        id: extract_metadata_alpine
        uses: docker/metadata-action@v4.1.0
        with:
          images: ${{ env.registry }}/${{ env.image_name }}
          flavor: suffix=-alpine,onlatest=true

      - name: Setup Buildx for caching
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image for Ubuntu version
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.extract_metadata_ubuntu.outputs.tags }}
          labels: ${{ steps.extract_metadata_ubuntu.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Docker image for Alpine version
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          file: docker/Dockerfile.alpine
          push: true
          tags: ${{ steps.extract_metadata_alpine.outputs.tags }}
          labels: ${{ steps.extract_metadata_alpine.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
